// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdX44R18yHzV0dl_YDRPaO2uMJAVj_pNc',
    appId: '1:868993717361:web:34e95404fe0eeee88077d0',
    messagingSenderId: '868993717361',
    projectId: 'kitchen-alchemy-f3fd1',
    authDomain: 'kitchen-alchemy-f3fd1.firebaseapp.com',
    storageBucket: 'kitchen-alchemy-f3fd1.firebasestorage.app',
    measurementId: 'G-G6RSXC0KF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbtzJ-RX9jx484bymhso8ErreGZmlUjD8',
    appId: '1:868993717361:android:3002ef46dbe6e1838077d0',
    messagingSenderId: '868993717361',
    projectId: 'kitchen-alchemy-f3fd1',
    storageBucket: 'kitchen-alchemy-f3fd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFCigoAyFjtEk6FIInLllDvplXOJA6X8A',
    appId: '1:868993717361:ios:821079a72aadab8a8077d0',
    messagingSenderId: '868993717361',
    projectId: 'kitchen-alchemy-f3fd1',
    storageBucket: 'kitchen-alchemy-f3fd1.firebasestorage.app',
    iosBundleId: 'com.ezeklawapps.kitchenalchemy.kitchenAlchemy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFCigoAyFjtEk6FIInLllDvplXOJA6X8A',
    appId: '1:868993717361:ios:821079a72aadab8a8077d0',
    messagingSenderId: '868993717361',
    projectId: 'kitchen-alchemy-f3fd1',
    storageBucket: 'kitchen-alchemy-f3fd1.firebasestorage.app',
    iosBundleId: 'com.ezeklawapps.kitchenalchemy.kitchenAlchemy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdX44R18yHzV0dl_YDRPaO2uMJAVj_pNc',
    appId: '1:868993717361:web:6defdb002d91647c8077d0',
    messagingSenderId: '868993717361',
    projectId: 'kitchen-alchemy-f3fd1',
    authDomain: 'kitchen-alchemy-f3fd1.firebaseapp.com',
    storageBucket: 'kitchen-alchemy-f3fd1.firebasestorage.app',
    measurementId: 'G-M8P1S5NR31',
  );
}
